<?php
/*
* File:			report.php
* Version:		-
* Last changed:	2016/04/13
* Purpose:		-
* Author:		Fisher Liao / fisher.liao@gmail.com
* Copyright:	(C) 2016
* Product:		NFW
*/
class Report extends CI_Controller {
	public function __construct() {
		parent::__construct();
		$this->load->model('report_model');
		$this->load->helper('url');
	}

	public function doc1() {
		if($this->session->userdata('role') === FALSE) {
			show_error('',401);
		}

		$this->load->library('PHPExcel');

		$rpt_type = $this->input->post('hid_report_type');

        // Create new PHPExcel object
        $objPHPExcel = new PHPExcel();

        // Set document properties
        $objPHPExcel->getProperties()->setCreator("Fisher Liao")
                                     ->setLastModifiedBy("Fisher Liao")
                                     ->setTitle("Office 2007 XLSX Document")
                                     ->setSubject("Office 2007 XLSX Document")
                                     ->setDescription("Generated By NFW Project, Developed By IT Team")
                                     ->setKeywords("office 2007 openxml php")
                                     ->setCategory("result file");
		// Add some data
		$objPHPExcel->setActiveSheetIndex(0);
		$sheet = $objPHPExcel->getActiveSheet();

		// header
		$sheet->mergeCells('A1:Q1');
		$sheet->setCellValue('A1', '函件對應勞工表');
		$sheet->mergeCells('A2:Q2');
		$sheet->setCellValue('A2', '製表人：'.$this->session->userdata('account').' 製表日期：'.date('Y-m-d'));
		$ary_head = array(
			'序',
			'客戶',
			'雇主',
			'招募許可函函號',
			'招募許可函發文日期',
			'招募許可函到期日期',
			'招募許可函工期',
			'入國引進許可函函號',
			'入國引進許可函發文日期',
			'入國引進許可函到期日期',
			'認證牌照',
			'工別',
			'工種',
			'學號',
			'中文姓名',
			'英文姓名',
			'實際入境日期'
		);
		$sheet->fromArray(
			$ary_head,  // The data to set
			NULL,        // Array values with this value will not be set
			'A3'         // Top left coordinate of the worksheet range where
		);

		// data
		$ary_data = $this->report_model->getDoc1();

		//echo $this->db->last_query();exit;
		//var_dump($ary_data);exit;

		$sheet->fromArray(
			$ary_data,  // The data to set
			NULL,        // Array values with this value will not be set
			'A4'         // Top left coordinate of the worksheet range where
		);

		// alignment
		$sheet->getStyle('A1')->getAlignment()->applyFromArray(
			array('horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_CENTER)
		);
		$sheet->getStyle('A2')->getAlignment()->applyFromArray(
			array('horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_RIGHT)
		);

		// font
		$sheet->getStyle('A1')->getFont()->setSize(14)->setBold(true);

		// line
		$sheet->getStyle('A1:Q2')->getBorders()->getAllborders()->setBorderStyle(PHPExcel_Style_Border::BORDER_THIN);

		// Rename worksheet
		$objPHPExcel->getActiveSheet()->setTitle('x');

		$objDrawing = new PHPExcel_Worksheet_Drawing();
		$objDrawing->setName('logo');
		$objDrawing->setDescription('logo');
		$objDrawing->setPath('./assets/img/logo_word.png');
		$objDrawing->setHeight(72);
		$objDrawing->setCoordinates('A1');
		$objDrawing->setOffsetX(10);
		$objDrawing->setWorksheet($objPHPExcel->getActiveSheet());
		$objDrawing->getShadow()->setVisible(true);
		$objDrawing->getShadow()->setDirection(45);

		$objWriter = new PHPExcel_Writer_Excel2007($objPHPExcel); 
		$objWriter->save('/var/www/html/nfw/uploads/report.xlsx');

		$response = array(
		    'success' => true,
		    'url' => base_url().'uploads/report.xlsx'
		);

		header('Content-type: application/json');

		// and in the end you respond back to javascript the file location
		echo json_encode($response);
	}

	public function doc2() {
		if($this->session->userdata('role') === FALSE) {
			show_error('',401);
		}

		// data
		$ary_data = $this->report_model->getDoc2();

		$this->load->library('PHPExcel');

		$rpt_type = $this->input->post('hid_report_type');

        // Create new PHPExcel object
        $objPHPExcel = new PHPExcel();

        // Set document properties
        $objPHPExcel->getProperties()->setCreator("Fisher Liao")
                                     ->setLastModifiedBy("Fisher Liao")
                                     ->setTitle("Office 2007 XLSX Document")
                                     ->setSubject("Office 2007 XLSX Document")
                                     ->setDescription("Generated By NFW Project, Developed By IT Team")
                                     ->setKeywords("office 2007 openxml php")
                                     ->setCategory("result file");
		// Add some data
		$objPHPExcel->setActiveSheetIndex(0);
		$sheet = $objPHPExcel->getActiveSheet();

		// header
		$sheet->mergeCells('A1:N1');
		$sheet->setCellValue('A1', '函件管理明細表');
		$sheet->mergeCells('A2:N2');
		$sheet->setCellValue('A2', '製表人：'.$this->session->userdata('account').' 製表日期：'.date('Y-m-d'));
		$sheet->mergeCells('A3:D3');
		$sheet->mergeCells('M3:N3');
		$sheet->mergeCells('E3:H3');
		$sheet->setCellValue('E3', '招募許可函');	
		$sheet->mergeCells('I3:L3');
		$sheet->setCellValue('I3', '入國引進許可函');				
		$ary_head = array(
			'序',
			'國別',
			'客戶',
			'雇主',
			'函號',
			'名額',
			'到期日期',
			'案件狀態',
			'函號',
			'名額',
			'到期日期',
			'案件狀態',
			'客服員',
			'業務員'
		);
		$sheet->fromArray(
			$ary_head,  // The data to set
			NULL,        // Array values with this value will not be set
			'A4'         // Top left coordinate of the worksheet range where
		);


		//echo $this->db->last_query();exit;
		//var_dump($ary_data);exit;

		$sheet->fromArray(
			$ary_data,  // The data to set
			NULL,        // Array values with this value will not be set
			'A5'         // Top left coordinate of the worksheet range where
		);

		// alignment
		$sheet->getStyle('A1')->getAlignment()->applyFromArray(
			array('horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_CENTER)
		);
		$sheet->getStyle('A2')->getAlignment()->applyFromArray(
			array('horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_RIGHT)
		);
		$sheet->getStyle('E3')->getAlignment()->applyFromArray(
			array('horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_CENTER)
		);
		$sheet->getStyle('I3')->getAlignment()->applyFromArray(
			array('horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_CENTER)
		);

		// font
		$sheet->getStyle('A1')->getFont()->setSize(14)->setBold(true);

		// line
		$sheet->getStyle('A1:N4')->getBorders()->getAllborders()->setBorderStyle(PHPExcel_Style_Border::BORDER_THIN);

		// Rename worksheet
		$objPHPExcel->getActiveSheet()->setTitle('x');

		$objDrawing = new PHPExcel_Worksheet_Drawing();
		$objDrawing->setName('logo');
		$objDrawing->setDescription('logo');
		$objDrawing->setPath('./assets/img/logo_word.png');
		$objDrawing->setHeight(72);
		$objDrawing->setCoordinates('A1');
		$objDrawing->setOffsetX(10);
		$objDrawing->setWorksheet($objPHPExcel->getActiveSheet());
		$objDrawing->getShadow()->setVisible(true);
		$objDrawing->getShadow()->setDirection(45);

		$objWriter = new PHPExcel_Writer_Excel2007($objPHPExcel); 
		$objWriter->save('/var/www/html/nfw/uploads/report.xlsx');

		$response = array(
		    'success' => true,
		    'url' => base_url().'uploads/report.xlsx'
		);

		header('Content-type: application/json');

		// and in the end you respond back to javascript the file location
		echo json_encode($response);
	}

	public function doc3() {
		if($this->session->userdata('role') === FALSE) {
			show_error('',401);
		}

		// data
		$ary_data = $this->report_model->getDoc3();

		$this->load->library('PHPExcel');

		$rpt_type = $this->input->post('hid_report_type');

        // Create new PHPExcel object
        $objPHPExcel = new PHPExcel();

        // Set document properties
        $objPHPExcel->getProperties()->setCreator("Fisher Liao")
                                     ->setLastModifiedBy("Fisher Liao")
                                     ->setTitle("Office 2007 XLSX Document")
                                     ->setSubject("Office 2007 XLSX Document")
                                     ->setDescription("Generated By NFW Project, Developed By IT Team")
                                     ->setKeywords("office 2007 openxml php")
                                     ->setCategory("result file");
		// Add some data
		$objPHPExcel->setActiveSheetIndex(0);
		$sheet = $objPHPExcel->getActiveSheet();

		// header
		$sheet->mergeCells('A1:M1');
		$sheet->setCellValue('A1', '聘工報表');
		$sheet->mergeCells('A2:M2');
		$sheet->setCellValue('A2', '製表人：'.$this->session->userdata('account').' 製表日期：'.date('Y-m-d'));
			
		$ary_head = array(
			'序',
			'國別',
			'客戶',
			'雇主',
			'下單日期',
			'聘工單號',
			'性別',
			'工種',
			'類別',
			'需求人數',
			'工作期限',
			'客服員',
			'業務員'
		);
		$sheet->fromArray(
			$ary_head,  // The data to set
			NULL,        // Array values with this value will not be set
			'A3'         // Top left coordinate of the worksheet range where
		);


		//echo $this->db->last_query();exit;
		//var_dump($ary_data);exit;

		$sheet->fromArray(
			$ary_data,  // The data to set
			NULL,        // Array values with this value will not be set
			'A4'         // Top left coordinate of the worksheet range where
		);

		// alignment
		$sheet->getStyle('A1')->getAlignment()->applyFromArray(
			array('horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_CENTER)
		);
		$sheet->getStyle('A2')->getAlignment()->applyFromArray(
			array('horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_RIGHT)
		);
		$sheet->getStyle('E3')->getAlignment()->applyFromArray(
			array('horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_CENTER)
		);
		$sheet->getStyle('I3')->getAlignment()->applyFromArray(
			array('horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_CENTER)
		);

		// font
		$sheet->getStyle('A1')->getFont()->setSize(14)->setBold(true);

		// line
		$sheet->getStyle('A1:M3')->getBorders()->getAllborders()->setBorderStyle(PHPExcel_Style_Border::BORDER_THIN);

		// Rename worksheet
		$objPHPExcel->getActiveSheet()->setTitle('x');

		$objDrawing = new PHPExcel_Worksheet_Drawing();
		$objDrawing->setName('logo');
		$objDrawing->setDescription('logo');
		$objDrawing->setPath('./assets/img/logo_word.png');
		$objDrawing->setHeight(72);
		$objDrawing->setCoordinates('A1');
		$objDrawing->setOffsetX(10);
		$objDrawing->setWorksheet($objPHPExcel->getActiveSheet());
		$objDrawing->getShadow()->setVisible(true);
		$objDrawing->getShadow()->setDirection(45);

		$objWriter = new PHPExcel_Writer_Excel2007($objPHPExcel); 
		$objWriter->save('/var/www/html/nfw/uploads/report.xlsx');

		$response = array(
		    'success' => true,
		    'url' => base_url().'uploads/report.xlsx'
		);

		header('Content-type: application/json');

		// and in the end you respond back to javascript the file location
		echo json_encode($response);
	}

}